### ISSUE TITLE
Way to hide attributes tooltip

### ISSUE THREAD

**Issue by jakeb072001** [emilyploszaj/trinkets#163]
Is there any way to hide the attributes tooltip on an item? I have 5 trinket slots that my trinkets can be equipped into but because of this my attribute tooltip displays 5 times.

![Screenshot (191)](https://user-images.githubusercontent.com/19660276/163421947-ab118d7e-dcb8-4c89-aba7-374a5dff89fc.png)

Am I doing something wrong or is there something I need to do to help with this or should I try to use a mixin?

**Comment by emilyploszaj** [comment]
There are several solutions to this bloat. For one, if your accessory slots have the same translated name ("Accessory Slot" instead of being numbered) and the info is the same, it will be merged under one description. In another case, if you have a slot that has an amount of 5 instead of adding 5 slots, this is also the behavior. Additionally, if your item can be equipped in any available trinket slot and provide bonuses there, it will display "when equipped in any trinket slot" instead of naming the specific one. If you do truly want to have 5 similarly but not identically named slots that can gain the same effects from the same item while also having it be equipable in slots where it does not gain effects, Trinkets does not provide a solution.

**Comment by jakeb072001** [comment]
If I set all the translated names to be the exact same it still lists the attributes for each slot, not really sure why. I also did try setting the amount to 5 but I don't really like how it extends vertically, but I could do that for now until I figure something out.

**Comment by jakeb072001** [comment]
Just wanted to say that all I had to do was set tooltip_predicates to trinkets:none, I guess I should have explained what it is I wanted better, but its working fine now.
