### ISSUE TITLE
Trinkets not respecting DropRules

### ISSUE THREAD

**Issue by Tiviacz1337** [emilyploszaj/trinkets#177]
Hi, I'm a developer and found weird bug with Trinkets. It turns out trinket do not respect set DropRule. In every case the item just drops on the ground. Could you check that? Maybe my implementation is wrong, but I've looked at other mods and it seems to be just right

**Comment by emilyploszaj** [comment]
What are you doing to modify the drop rules? is this for certain slots or are you doing something in code?

**Comment by Tiviacz1337** [comment]
I use Trinket#getDropRule on my implementation of trinkets for item. It's for item not slot

**Comment by Tiviacz1337** [comment]
Any updates on this issue? I don't know If I can release mod update or it'll be patched - of course if it's not issue from my side

**Comment by emilyploszaj** [comment]
It looks like the default behavior of your mod is to have the "trinkets integration" disabled behind a config flag. Because trinkets slots and equipability is denoted through a tag, it's very possible you haven't set this to true to enable your config, which registers your items as having an implementation of `Trinket` to get the drop rule. My guess is you currently have the trinkets integration disabled. If this is the case, I suggest you use the config to conditionally load an extra trinkets integration datapack at launch so that you can't equip it and have slots added without the integration being enabled, causing this same confusion.

**Comment by Tiviacz1337** [comment]
Fixed
