### ISSUE TITLE
Trinkets 3.7.2 causes item loss/dupe with Travellers Backpack

### ISSUE THREAD

**Issue by Ghostlyr** [emilyploszaj/trinkets#298]
1.20.1 Fabric 0.15.7, API 0.91.0
trinkets-3.7.2
travelers-backpack-1.20.1-9.1.9

After updating from trinkets 3.7.1 I started having problems with Travellers Backpack (with enabled trinkets integration):
Items added to the backpack are lost after the GUI is closed, and at the same time if you take items from it and close, some will remain in place 

@powerboat9
https://github.com/emilyploszaj/trinkets/commit/4a61ae8c63e645a553f7ffb93ff2217b9a767842

Is this possibly caused by this commit?

**Comment by TheIllusiveC4** [comment]
You should report this to the Traveler's Backpack developer(s) instead for further investigation.

> Is this possibly caused by this commit?

Highly unlikely as that change would have only affected non-player entities.

**Comment by LeeThorogood** [comment]
This appears to have been caused by #296 

I have reproduced the reported behaviour on 1.20.1 with Trinkets 3.7.2 and Travelers Backpack 9.1.9, as well as on 1.20.4 with Trinkets 3.8.1 and Travelers Backpack 9.40. In both instances the Travelers Backpack config option 'trinketsIntegration'  was set to 'true'.

I was able to resolve the issue in both instances by reverting the changes made to LivingEntityMixin.tick(CallbackInfo) in #296, and replacing the trinkets-3.x.x.jar in my respective mod folders with the newly compiled ones from my respective build/libs folders.

**Comment by emilyploszaj** [comment]
https://github.com/Tiviacz1337/Travelers-Backpack/blob/1.20.1-fabric/src/main/java/com/tiviacz/travelersbackpack/compat/trinkets/TravelersBackpackTrinket.java#L40 This is the cause of this issue, they're only updating the contents when onEquipped is called, which was the old "broken" behavior, I think they'll have to do updates in tick and it should be reported to them.
